services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend-network
    environment:
      NEXT_APP_API_URL: ${NEXT_APP_API_URL}
      NODE_ENV: development
      WATCHPACK_POLLING: true

networks:
  frontend-network:
    driver: bridge
